### ISSUE TITLE
Rename Makefile targets

### ISSUE THREAD

**Issue by ericof** [plone/cookiecutter-volto#14]
For all targets, follow the pattern `<component|tool>-<action>-<environment>`

**Comment by ericof** [comment]
@stevepiercy, @davisagli, @sneridagh, these are my suggestions:

```text
help                                 Show this help
install                              Installs the dev environment using mrs-developer
start                                Starts the add-on in development mode
build                                Build a production bundle for the project containing the add-on
i18n                                 Sync i18n
format                               Format codebase
lint                                 Lint Codebase
release                              Release the add-on on npmjs.org
release-dry-run                      Dry-run the release of the add-on on npmjs.org
test                                 Run unit tests
test-ci                              Run unit tests in CI
storybook-start                      Start Storybook server on port 6006
storybook-build                      Build Storybook
backend-start-docker                 Starts a Docker-based backend for developing
acceptance-frontend-start-dev        Start acceptance frontend in dev mode
acceptance-frontend-start            Start acceptance frontend in prod mode
acceptance-backend-start             Start backend acceptance server
acceptance-test                      Start Cypress in interactive mode
acceptance-test-headless             Run cypress tests in headless mode for CI
```

Opinions?

**Comment by stevepiercy** [comment]
Setting aside the non-descriptive descriptions for now (I prefer verbose to vague), I would prefer a pattern of `thing-subthing-subsubthing-action` for the Make target names. For most of the commands, it is more convenient to use a short name instead of a more descriptive name, as they are the most common or default. For example, `test` and `test-ci` are the most common tests to run, so a name like `unit-test` and `unit-ci-test` would be annoying. The naming convention needs flexibility.

Here's the names I would change. As long as you know that the action is always the last segment, and that thingies are the first segments, it will be easier for developers.

```
ci-test                              Run unit tests in CI
backend-docker-start                 Starts a Docker-based backend for developing
acceptance-frontend-dev-start        Start acceptance frontend in development mode
acceptance-frontend-prod-start       Start acceptance frontend in production mode
acceptance-headless-test             Run cypress tests in headless mode for CI
```

**Comment by sneridagh** [comment]
@stevepiercy  `ci-test` sounds wrong to me :( Also it's something that normally users don't do (at least me, it seems that people around use that command locally :)

**Comment by tisto** [comment]
@ericof LGTM. However, can you elaborate on the difference between "install" and "build"? I don't get this. I also don't get why "build" builds the production bundle and not the "dev bundle". I do not want to look into the details here since I am trying to look at those commands like a newbie. :)

**Comment by stevepiercy** [comment]
@sneridagh "test" in this context is a verb or action. I much prefer a naming pattern where the thing to be acted on comes first, and is followed by the action to perform on the thing.

**Comment by ericof** [comment]
@stevepiercy I defer to your expertise and experience here :-)
That being said, could you simply copy the list in the first command and replace where adequate?
I will implement that on Monday

**Comment by stevepiercy** [comment]
To document the rules:

1. Use kebab-case, where each word is separated by a hyphen.
2. Use [hierarchical or taxonomic ranking](https://johnfarrier.com/a-practical-guide-for-naming-things/#h-taxonomic-ranking-in-naming), where the thing being operated upon is defined by `[thing]`-`[subthing]`-`[subsubthing]`.
3. `[thing]` may be omitted when it is the project itself.
4. The final term is the `action` to be performed upon the `[thing]`.

I also polished up the descriptions.

```
help                                 Show this help
install                              Installs the add-on in a development environment
start                                Starts Volto, allowing reloading of the add-on during development
build                                Build a production bundle for distribution of the project with the add-on
i18n                                 Sync i18n
format                               Format code base
lint                                 Lint, or catch and remove problems, in code base
release                              Release the add-on on npmjs.org
release-dry-run                      Dry-run the release of the add-on on npmjs.org
test                                 Run unit tests
ci-test                              Run unit tests in CI
storybook-start                      Start Storybook server on port 6006
storybook-build                      Build Storybook
backend-docker-start                 Starts a Docker-based backend for development
acceptance-frontend-dev-start        Start acceptance frontend in development mode
acceptance-frontend-prod-start       Start acceptance frontend in production mode
acceptance-backend-start             Start backend acceptance server
acceptance-headless-test             Run cypress tests in headless mode for CI
acceptance-test                      Start Cypress in interactive mode
ci-acceptance-backend-start          Start backend acceptance server in headless mode for CI
```

**Comment by jensens** [comment]
I would use `check` instead of `lint`. Latter is jargon, first is within a beginners English vocabulary.

**Comment by stevepiercy** [comment]
"Lint" is a common English term in the context of software programming. See https://en.wikipedia.org/wiki/Lint_(software). `check` is too vague.

**Comment by jensens** [comment]
However, asking i.e. Deepl gives no meaningful answer (German: Fussel/ fusseln). 

At least the description should be meaningful then.

**Comment by stevepiercy** [comment]
Updated to:

```
lint                                 Lint, or catch and remove problems, in code base
```

The term derives from a clothes drier filter that catches and removes lint from clothing through forced air and a wire screen.

**Comment by ericof** [comment]
Closing this, as it was implemented in cookieplone-templatea
